#Various operations on numpy array 
import numpy as np
arr = np.arange(1,11)
print("Original array arr is ")
print(arr)
print("Multilying array arr by 2 and printing ")
print(arr*2)
print("Adding each element of arr with 2")
print(arr+2)
print("Squaring each element of arr ")
print(arr**2)
print("Cubing each element of arr ")
print(arr**3)
#In numpy array divide any element by 0 gives infinity not error
print("Dividing each element of arr by 0 and checking the results ")
print(arr/0)
print("Creating a new array ayy")
ayy = np.arange(11,21)
print("Printing ayy ")
print(ayy)
print("Adding arr and ayy ")
print(arr+ayy)
print("Substracting ayy from arr ")
print(arr - ayy)
#Operation on two dimensional array
print(" Making two dimensional array a and b ")
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
print(" print array a ")
print(a)
print("Printing array b")
print(b)
print("Adding a with b ")
print(a+b)
print("Substracting a from b")
print(a-b)
print("Dividing array b by a")
print(b/a)
print("Multiplying array a to b")
print(a*b)
print("For multiplication of two matrices we will perform dot product ")
print("a.dot(b)")
print(a.dot(b))