#Sum more important functions in numpy Part 1
import numpy as np
arr = np.array([10,20,30,40,50])
print("Original array is ","\n",arr)
print("To print minimum from this array we will use min() function ")
print(np.min(arr))
print("To print maximum from this array we will use max() function ")
print(np.max(arr))
print("To print position of minimum number we will use argmin() function")
print(np.argmin(arr))
print("To print position of maximum number we will use argmax() function ")
print(np.argmax(arr))
print("To print square root of every number we will use sqrt() function ")
print(np.sqrt(arr))
print("To print sin value of every number we will use sin() function ")
print(np.sin(arr))
print("To print cos value of every number we will use cos() function ")
print(np.cos(arr))
print("Using linspace() function ")
print(" code is np.linspace(1,2,5) , output is ")
print(np.linspace(1,2,5))